CREATE TABLE [User]
(
[UserID] VARCHAR(8) PRIMARY KEY NOT NULL UNIQUE,
[Name] VARCHAR(25) NOT NULL,
[Password] VARCHAR(25) NOT NULL,
[Privilege] VARCHAR (30) NOT NULL
);

CREATE TABLE [File]
(
[FileID]VARCHAR (8) PRIMARY KEY NOT NULL UNIQUE,
[FileName] VARCHAR (25) NOT NULL UNIQUE,
[FileOwner] VARCHAR (25) NOT NULL,
[DateCreated] VARCHAR (10) NOT NULL,
[Shared] VARCHAR (1) NOT NULL,
[FileLocation] VARCHAR (100) NOT NULL UNIQUE,
FOREIGN KEY(FileOwner) REFERENCES User(Name)
);

INSERT INTO User VALUES('1', 'Josh', 'Password', 'DMS');
